version: "1"
services:
  - type: web
    name: dwarf-backend
    runtime: docker
    plan: free
    region: virginia
    repo: https://github.com/nasserjawabreh9-sys/Dwarf
    rootDir: Backend
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: false
    healthCheckPath: /healthz
