version: "1"
services:
  - type: web
    name: Dwarf-1
    runtime: docker
    plan: free
    region: virginia
    repo: https://github.com/nasserjawabreh9-sys/Dwarf

    # IMPORTANT: your folder is "backend" (lowercase), not "Backend"
    rootDir: backend
    dockerContext: .
    dockerfilePath: Dockerfile

    autoDeploy: false
    healthCheckPath: /healthz
